### PR TITLE
Enable dependabot to automatically get dependency updates

### PR DESCRIPTION
**Pull request by MRamonLeon**
It would be great to have **Dependabot** configured to get dependencies updates filed automatically. This will help avoiding bugs or security vulnerabilities from old dependencies.

Some helpful documentation about Dependabot to fine adjust it if needed:

* Keeping your dependencies updated automatically: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically
* Avoiding security vulnerabilities: https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates
* Fine adjusting the configuration: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

### CODE REVIEW

**Comment by MRamonLeon** [comment]
cc: @oleg-nenashev @jglick

**Review by oleg-nenashev — DISMISSED** [review]
This pattern would lead dependabot to suggest Jenkins core dependency upgrades. Please add it to the ignore list

**Comment by jglick** [comment]
> This pattern would lead dependabot to suggest Jenkins core dependency upgrades.

No, it does not.

**Review by jglick — APPROVED** [review]

**Review by kuisathaverat — APPROVED** [review]

**Comment by kuisathaverat** [comment]
as soon as @oleg-nenashev approve it I will merge it

**Review by oleg-nenashev — APPROVED** [review]
> No, it does not.

Hmm, really? Not clear why, but I do not want to block it. can be fixed later

**Comment by jglick** [comment]
> Not clear why

I think because while the _property_ is defined in the visible POM, the _dependency_ is defined in the parent, and Dependabot does not try to resolve the effective POM—it does not do the precise analysis that

```bash
mvn versions:display-dependency-updates
```

would.

**Comment by jglick** [comment]
Thus our stock recommendation: https://github.com/jenkinsci/archetypes/blob/61e835797f4c8318336b37aaa107eedac62dd6ce/common-files/.github/dependabot.yml

**Comment by oleg-nenashev** [comment]
> I think because while the *property* is defined in the visible POM, the
*dependency* is defined in the parent, and Dependabot does not try to
resolve the effective POM—it does not do the precise analysis that

It was definitely doing it before for Jenkins core. Maybe there was a
regression in Dependabot at some point, I have noticed some degradation in
"GitHub-native dependabot" for other projects. Some features are still not
available in the new edition.

BR, Oleg

**Comment by jglick** [comment]
BTW I strongly recommend switching to https://github.com/jenkinsci/bom#usage

**Comment by kuisathaverat** [comment]
@jglick when I bump the core version I will do it, as I did for [trilead-api](https://github.com/jenkinsci/trilead-api-plugin/commit/f4a23faaa144d25a09c3d3d9e13224fd3005a532)

**Pull request merged**
