### PR TITLE
Before connect script implemented

### PR DESCRIPTION
**Pull request by bubenkoff**
[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/ssh-slaves-plugin/16)

### CODE REVIEW

**Comment by nixpanic** [comment]
I would really like to see this feature included. The idea is to shutdown/poweroff the slave when a disconnect is done, and start it again upon reconnect. The Rackspace cloud API should make this quite easy.

Is there anything I (or someone else who is interested) can do to get this feature accepted?

**Comment by nixpanic** [comment]
I would really like to see this feature included. The idea is to shutdown/poweroff the slave when a disconnect is done, and start it again upon reconnect. The Rackspace cloud API should make this quite easy.

Is there anything I (or someone else who is interested) can do to get this feature accepted?

**Comment by bubenkoff** [comment]
@nixpanic this is exactly how it's used by us (paylogic) :)
my bad that i haven't rebased this feature branch onto the master yet - that's what you can help with

**Comment by bubenkoff** [comment]
@nixpanic i can give you collaborator access for our fork

**Comment by nixpanic** [comment]
Access would be nice, but I can also take your branch and start my own
fork based on that. I'm happy to do the rebase and update this pull
request and/or create a new one. Just let me know what you prefer.

Thanks!

**Comment by bubenkoff** [comment]
ok that works as well of course (about your fork)
and actually better because of gh permission system (i cannot give you access without adding you to the org)

**Comment by olivergondza** [comment]
To me it seems this would be better implemented in separate plugin to invoke *any* action before of after *any* launch attempt. Given how old this is and it does not merge clearly, I presume this is no longer needed.

**Pull request closed without merging**
