### PR TITLE
[JENKINS-42022] Remove 'unix machines' from plugin's description.

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-42022](https://issues.jenkins-ci.org/browse/JENKINS-42022)

Adapt descriptions in POM and index.jelly files after  [PR #33](https://github.com/jenkinsci/ssh-slaves-plugin/pull/33)

@reviewbybees @stephenc @olamy

### CODE REVIEW

**Comment by varyvol** [comment]
@stephenc @olamy could you please kindly review this?

**Comment by varyvol** [comment]
@stephenc @olamy ping?

**Comment by varyvol** [comment]
@stephenc I think this one is ready to be merged.

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
