### PR TITLE
[JENKINS-55787] Switch labels from entry to checkbox

### PR DESCRIPTION
**Pull request by jsoref**
[https://issues.jenkins-ci.org/browse/JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)

Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.

This supersedes #117

### CODE REVIEW

**Comment by kuisathaverat** [comment]
Could you please attach a screen capture of how to it is showing it before and after in relation with the rest of fields?  I think it breaks the form view.

**Comment by jsoref** [comment]
Today:
image
With this patch:
image

Going forward as part of jenkinsci/jenkins#3895:
image

**Comment by kuisathaverat** [comment]
it without https://github.com/jenkinsci/jenkins/pull/3895 it looks weird, but I like it too much with the whole solution. The only NIT is the help button. So I will monitor the 3895 and as soon it was merged this will be merged

**Comment by jsoref** [comment]
@kuisathaverat : btw, do you have any particular input on the help button? -- See https://github.com/jenkinsci/jenkins/pull/3895#issuecomment-464588474

**Comment by kuisathaverat** [comment]
I saw that https://github.com/jenkinsci/jenkins/pull/3895 is closed so I guess this one has to be closed too, isn't it?

**Comment by jsoref** [comment]
I still intend to get it done eventually. I might even try to poke the UX SIG this week.

**Comment by kuisathaverat** [comment]
cool, I'll keep it open

**Comment by kuisathaverat** [comment]
Without the change
Screenshot 2021-05-01 at 12 30 46

With the change
Screenshot 2021-05-01 at 12 33 07

@jsoref
The changes you made on the core are so good that the PR is not needed anymore, thank you, if you are OK we can close the PR.

**Pull request closed without merging**
