### PR TITLE
[JENKINS-38832] Add support for credential tracking.

### PR DESCRIPTION
**Pull request by iwarapter**
https://issues.jenkins-ci.org/browse/JENKINS-38832

### CODE REVIEW

**Comment by jglick** [comment]
```
Possible null pointer dereference in hudson.plugins.sshslaves.SSHLauncher.launch(SlaveComputer, TaskListener) due to return value of called method [hudson.plugins.sshslaves.SSHLauncher, hudson.plugins.sshslaves.SSHLauncher] Method invoked at SSHLauncher.java:[line 745]Known null at SSHLauncher.java:[line 744] NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
Nullcheck of node at line 745 of value previously dereferenced in hudson.plugins.sshslaves.SSHLauncher.launch(SlaveComputer, TaskListener) [hudson.plugins.sshslaves.SSHLauncher, hudson.plugins.sshslaves.SSHLauncher] At SSHLauncher.java:[line 745]Redundant null check at SSHLauncher.java:[line 746] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
```

**Comment by oleg-nenashev** [comment]
@iwarapter pong

**Comment by iwarapter** [comment]
@oleg-nenashev Sorry i forgot to push the change after @jglick's comment

**Comment by stephenc** [comment]
👍  on bumping the core dep to align with credential's core dep

**Comment by iwarapter** [comment]
Any update on this guys?

**Comment by oleg-nenashev** [comment]
@iwarapter there is a merge conflict. It would be great if you could fix it (though a plugin maintainer can do it as well)

**Comment by iwarapter** [comment]
@oleg-nenashev this is updated now.

**Comment by oleg-nenashev** [comment]
Yes, I've seen the update. Now it needs an action from a maintainer. CC @olivergondza and @jglick

**Comment by oleg-nenashev** [comment]
Fixed the merge conflict

**Comment by oleg-nenashev** [comment]
Now it's ready to go

**Pull request merged**
