### PR TITLE
Bump BOM, baseline

### PR DESCRIPTION
**Pull request by jglick**
Closes #363. Closes #381.

### CODE REVIEW

**Comment by kuisathaverat** [comment]
no objection to merge it 😄

**Comment by kuisathaverat** [comment]
@jglick What is the urgency to release a version?

**Comment by jglick** [comment]
To ship #352, mentioned in https://github.com/jenkinsci/plugin-compat-tester/pull/485.

Sorry if this was too fast, I did not realize anyone else was even paying attention to this plugin.

**Comment by kuisathaverat** [comment]
>Sorry if this was too fast, I did not realize anyone else was even paying attention to this plugin.

I did not make any new features for a while, but the plugins has its dependencies updated, was updated to Java 11 recently, and the usual bug fix and automation improvements. So I think it is in active maintenance by me.

**Pull request merged**
